import type { Lang } from './i18n';

const help = {
  en: {
    locations: { title: 'Map physical failure domains', body: 'Locations describe where devices really are. Build a hierarchy such as Company → Building A → Server room. Backup Planner uses it to recognize when every copy could be lost in the same incident.' },
    sources: { title: 'Define where original data lives', body: 'A source is the device or system that holds the original data, such as a laptop, server, NAS, phone, or cloud service. Every dataset starts at one source.' },
    targets: { title: 'Describe where copies are stored', body: 'A target is storage that receives a backup, synchronization, or archive. Its location and storage type are essential for the 3-2-1 assessment.' },
    datasets: { title: 'Name what needs protection', body: 'A dataset is a meaningful group such as Photos, Documents, or Virtual machines. Priority controls how strongly weaknesses affect the overall score.' },
    software: { title: 'Record the tool used', body: 'Software is optional documentation, for example Proxmox Backup Server, HBS, Restic, or Time Machine. Backup Planner never connects to or controls these tools.' },
    name: 'Use a clear, recognizable name. Names appear in plans, schedules, and recommendations.',
    locationType: 'Use Site for a general place, Building or Room for physical detail, and Cloud region for externally hosted storage.',
    parent: 'Choose the containing location. This creates a hierarchy and lets the analysis detect shared risks.',
    sourceLocation: 'The physical or cloud location of the device holding the original data.',
    deviceType: 'Describes the kind of source. It is documentation and does not grant the app access to the device.',
    targetLocation: 'Where this storage physically resides. Different rooms may reduce some risks; different sites provide stronger separation.',
    storageType: 'The storage technology. The 3-2-1 score rewards copies on at least two different storage types.',
    provider: 'Optional provider, facility, or descriptive place, such as Hetzner, Office NAS, or Safe deposit box.',
    immutable: 'Enable this if the target can prevent backup data from being changed or deleted during a defined period.',
    encrypted: 'Enable this if data on this target is normally stored encrypted.',
    datasetSource: 'The source on which the original version of this dataset lives.',
    priority: 'High-priority datasets count four times, Normal twice, and Low once in the overall protection score.',
    active: 'Inactive master data remains available to existing plans but is hidden when creating new ones.',
    notes: 'Optional context for people maintaining the backup plan. Do not store passwords or credentials here.',
    planDatasets: 'Select the concrete data covered by this plan. Only datasets assigned to the chosen source are shown. At least one dataset is required.',
    chooseSourceFirst: 'Choose a source first. Its assigned datasets will then appear here.',
    noDatasets: 'This source has no datasets yet. Create one in Settings → Datasets before saving the plan.',
    manageDatasets: 'Manage datasets',
    selectOne: 'Select at least one dataset to describe what this plan protects.',
  },
  de: {
    locations: { title: 'Physische Ausfallbereiche abbilden', body: 'Standorte beschreiben, wo Geräte tatsächlich stehen. Baue eine Hierarchie wie Firma → Gebäude A → Serverraum auf. Backup Planner erkennt damit, ob alle Kopien durch dasselbe Ereignis verloren gehen könnten.' },
    sources: { title: 'Ursprung der Originaldaten festlegen', body: 'Eine Quelle ist das Gerät oder System mit den Originaldaten, etwa Laptop, Server, NAS, Smartphone oder Cloud-Dienst. Jeder Datenbestand beginnt an einer Quelle.' },
    targets: { title: 'Speicherorte der Kopien beschreiben', body: 'Ein Ziel ist ein Speicher für Backup, Synchronisierung oder Archiv. Standort und Speichertyp sind entscheidend für die 3-2-1-Bewertung.' },
    datasets: { title: 'Schützenswerte Daten benennen', body: 'Ein Datenbestand ist eine sinnvolle Gruppe wie Fotos, Dokumente oder virtuelle Maschinen. Die Wichtigkeit bestimmt, wie stark Schwächen die Gesamtpunktzahl beeinflussen.' },
    software: { title: 'Verwendetes Werkzeug dokumentieren', body: 'Software ist eine optionale Dokumentation, etwa Proxmox Backup Server, HBS, Restic oder Time Machine. Backup Planner verbindet oder steuert diese Programme niemals.' },
    name: 'Verwende einen eindeutigen, gut erkennbaren Namen. Er erscheint in Plänen, Zeitplänen und Empfehlungen.',
    locationType: 'Standort bezeichnet einen allgemeinen Ort, Gebäude und Raum bilden physische Details ab, Cloud-Region steht für extern gehosteten Speicher.',
    parent: 'Wähle den übergeordneten Standort. So entsteht die Hierarchie, mit der gemeinsame Risiken erkannt werden.',
    sourceLocation: 'Der physische oder virtuelle Standort des Geräts mit den Originaldaten.',
    deviceType: 'Beschreibt die Art der Quelle. Dies dient nur der Dokumentation und gibt der App keinen Zugriff auf das Gerät.',
    targetLocation: 'Wo sich dieser Speicher physisch befindet. Verschiedene Räume reduzieren manche Risiken; getrennte Standorte schützen stärker.',
    storageType: 'Die Speichertechnologie. Für die 3-2-1-Bewertung sind mindestens zwei unterschiedliche Speichertypen vorteilhaft.',
    provider: 'Optionaler Anbieter, Aufstellort oder Zusatz, beispielsweise Hetzner, Büro-NAS oder Bankschließfach.',
    immutable: 'Aktivieren, wenn das Ziel Backup-Daten für einen festgelegten Zeitraum vor Änderung und Löschung schützen kann.',
    encrypted: 'Aktivieren, wenn Daten auf diesem Ziel normalerweise verschlüsselt gespeichert werden.',
    datasetSource: 'Die Quelle, auf der die ursprüngliche Version dieses Datenbestands liegt.',
    priority: 'Hohe Wichtigkeit zählt vierfach, Normal zweifach und Niedrig einfach in der Gesamtbewertung.',
    active: 'Inaktive Stammdaten bleiben in bestehenden Plänen erhalten, werden aber bei neuen Plänen nicht mehr angeboten.',
    notes: 'Optionaler Kontext für die Pflege des Backup-Plans. Keine Passwörter oder Zugangsdaten eintragen.',
    planDatasets: 'Wähle die konkreten Daten aus, die dieser Plan schützt. Angezeigt werden nur Datenbestände der gewählten Quelle. Mindestens ein Datenbestand ist erforderlich.',
    chooseSourceFirst: 'Wähle zuerst eine Quelle. Danach erscheinen hier die zugeordneten Datenbestände.',
    noDatasets: 'Für diese Quelle gibt es noch keine Datenbestände. Lege vor dem Speichern unter Einstellungen → Datenbestände einen an.',
    manageDatasets: 'Datenbestände verwalten',
    selectOne: 'Wähle mindestens einen Datenbestand aus, damit klar ist, welche Daten dieser Plan schützt.',
  },
} as const;

export function getHelp(lang: Lang) { return help[lang]; }
